# Generated by Django 4.2.21 on 2025-05-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friend_set", to="shop.profile"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
