# Generated by Django 4.2.21 on 2025-06-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="friends",
        ),
    ]
